Check for uncommitted files before releasing

diff --git a/scripts/dirty-repo-check b/scripts/dirty-repo-check
--- a/scripts/dirty-repo-check
+++ b/scripts/dirty-repo-check
@@ -1,5 +1,11 @@
 #!/bin/bash -eu
 git update-index -q --refresh
+if ! git diff-files --quiet --; then
+	echo '!!!'
+	echo '!!! ERROR uncommitted files in local repo'
+	echo '!!!'
+	exit 1
+fi
 if ! git diff-index --quiet HEAD --; then
 	echo '!!!'
 	echo '!!! ERROR local git repo has changes'
